services:
  - type: web
    name: bilbakalimonline
    runtime: dotnet
    configPath: BilBakalimOnline.csproj
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/BilBakalimOnline.dll"
